[package]
name = "aleo-explorer-rust"
version = "0.13.5"
edition = "2021"

[dependencies]

pyo3 = { version = "0.22.2", features = ["extension-module", "num-bigint"] }

num-bigint = "0.4.6"

snarkvm-algorithms = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-circuit-network = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-curves = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-console-account = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-console-network = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-console-program = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-synthesizer-program = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-utilities = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-ledger-puzzle = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-ledger-puzzle-epoch = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }
snarkvm-ledger-block = { git = "https://github.com/AleoNet/snarkVM", rev = "3d8b912e" }


#leo-compiler = { git = "https://github.com/AleoHQ/leo", rev = "ac3f667e19e15e84d704efa2ae5b948318361e00" }
#leo-errors = { git = "https://github.com/AleoHQ/leo", rev = "ac3f667e19e15e84d704efa2ae5b948318361e00" }
#leo-span = { git = "https://github.com/AleoHQ/leo", rev = "ac3f667e19e15e84d704efa2ae5b948318361e00" }

#leo-compiler = { git = "https://github.com/AleoHQ/leo", branch = "mainnet" }
#leo-errors = { git = "https://github.com/AleoHQ/leo", branch = "mainnet" }
#leo-span = { git = "https://github.com/AleoHQ/leo", branch = "mainnet" }
#leo-disassembler = { git = "https://github.com/AleoHQ/leo", branch = "mainnet" }
#leo-ast = { git = "https://github.com/AleoHQ/leo", branch = "mainnet" }

anyhow = "1.0.86"
rand = "0.8.5"
rand_chacha = "0.3.1"
bech32 = "0.11.0"
tempfile = "3.10.1"
indexmap = "1.9.3"

[build-dependencies]
pyo3-build-config = "0.22.2"

[lib]
crate-type = ["cdylib"]
name = "aleo_explorer_rust"

[profile.dev]
opt-level = 1
debug-assertions = false
