[package]
name = "aleo-python"
version = "0.7.0"
edition = "2021"

[dependencies]

pyo3 = { version = "0.19.0", features = ["extension-module"] }

snarkvm-algorithms = "0.12.4"
snarkvm-curves = "0.12.4"
snarkvm-console-account = "0.12.4"
snarkvm-console-network = "0.12.4"
snarkvm-console-program = "0.12.4"
snarkvm-synthesizer = "0.12.4"

leo-compiler = "1.7.0"
leo-errors = "1.7.0"
leo-span = "1.7.0"

rand = "0.8.5"
bech32 = "0.9.1"
tempfile = "3.5.0"

[build-dependencies]
pyo3-build-config = "0.19.0"

[lib]
crate-type = ["cdylib"]
name = "aleo"

[profile.dev]
opt-level = 1
debug-assertions = false