[package]
name = "aleo-explorer-rust"
version = "0.10.0-beta.2"
edition = "2021"

[dependencies]

pyo3 = { version = "0.20.0", features = ["extension-module", "num-bigint"] }

num-bigint = "0.4.4"

snarkvm-algorithms = "0.16.6"
snarkvm-curves = "0.16.6"
snarkvm-console-account = "0.16.6"
snarkvm-console-network = "0.16.6"
snarkvm-console-program = "0.16.6"
snarkvm-synthesizer-program = "0.16.6"
snarkvm-utilities = "0.16.6"

leo-compiler = "1.10.0"
leo-errors = "1.10.0"
leo-span = "1.10.0"

anyhow = "1.0.75"
rand = "0.8.5"
rand_chacha = "0.3.1"
bech32 = "0.9.1"
tempfile = "3.8.0"

[build-dependencies]
pyo3-build-config = "0.20.0"

[lib]
crate-type = ["cdylib"]
name = "aleo_explorer_rust"

[profile.dev]
opt-level = 1
debug-assertions = false
