[package]
name = "aleo-python"
version = "0.9.0"
edition = "2021"

[dependencies]

pyo3 = { version = "0.19.1", features = ["extension-module", "num-bigint"] }

num-bigint = "0.4.3"

snarkvm-algorithms = "0.14.5"
snarkvm-curves = "0.14.5"
snarkvm-console-account = "0.14.5"
snarkvm-console-network = "0.14.5"
snarkvm-console-program = "0.14.5"
snarkvm-synthesizer-program = "0.14.5"
snarkvm-utilities = "0.14.5"

leo-compiler = "1.9.1"
leo-errors = "1.9.1"
leo-span = "1.9.1"

anyhow = "1.0.72"
rand = "0.8.5"
rand_chacha = "0.3.1"
bech32 = "0.9.1"
tempfile = "3.7.0"

[build-dependencies]
pyo3-build-config = "0.19.1"

[lib]
crate-type = ["cdylib"]
name = "aleo"

[profile.dev]
opt-level = 1
debug-assertions = false
