[package]
name = "aleo-python"
version = "0.6.1"
edition = "2021"

[dependencies]

pyo3 = { version = "0.18.1", features = ["extension-module"] }

snarkvm = "0.11.2"
snarkvm-algorithms = "0.11.2"
snarkvm-curves = "0.11.2"
snarkvm-console-program = "0.11.2"
snarkvm-synthesizer = "0.11.2"

leo-compiler = "1.7.0"
leo-errors = "1.7.0"
leo-span = "1.7.0"

rand = "0.8.5"
bech32 = "0.9.1"
tempfile = "3.5.0"

[build-dependencies]
pyo3-build-config = "0.18.1"

[lib]
crate-type = ["cdylib"]
name = "aleo"

[profile.dev]
opt-level = 1
debug-assertions = false