[package]
name = "aleo-python"
version = "0.5.2"
edition = "2021"

[dependencies]

pyo3 = { version = "0.18.1", features = ["extension-module"] }

[dependencies.snarkvm]
version = "0.11.2"

[dependencies.snarkvm-algorithms]
version = "0.11.2"

[dependencies.snarkvm-curves]
version = "0.11.2"

[dependencies.snarkvm-console-program]
version = "0.11.2"

[dependencies.rand]
version = "0.8.5"

[dependencies.bech32]
version = "0.9.1"

[build-dependencies]
pyo3-build-config = "0.18.1"

[lib]
crate-type = ["cdylib"]
name = "aleo"

[profile.dev]
opt-level = 1
debug-assertions = false