[package]
name = "aleo-explorer-rust"
version = "0.10.0"
edition = "2021"

[dependencies]

pyo3 = { version = "0.20.0", features = ["extension-module", "num-bigint"] }

num-bigint = "0.4.4"

snarkvm-algorithms = "0.16.8"
snarkvm-curves = "0.16.8"
snarkvm-console-account = "0.16.8"
snarkvm-console-network = "0.16.8"
snarkvm-console-program = "0.16.8"
snarkvm-synthesizer-program = "0.16.8"
snarkvm-utilities = "0.16.8"

leo-compiler = { git = "https://github.com/AleoHQ/leo", rev = "1766c45ce10bd652e7847b645d66ab9105694800" }
leo-errors = { git = "https://github.com/AleoHQ/leo", rev = "1766c45ce10bd652e7847b645d66ab9105694800" }
leo-span = { git = "https://github.com/AleoHQ/leo", rev = "1766c45ce10bd652e7847b645d66ab9105694800" }

anyhow = "1.0.75"
rand = "0.8.5"
rand_chacha = "0.3.1"
bech32 = "0.9.1"
tempfile = "3.8.0"

[build-dependencies]
pyo3-build-config = "0.20.0"

[lib]
crate-type = ["cdylib"]
name = "aleo_explorer_rust"

[profile.dev]
opt-level = 1
debug-assertions = false
